### ISSUE TITLE
Display ID

### ISSUE THREAD

**Issue by richvanf** [kywalda/AIS-Radar#2]
I'm having trouble determining the correct SPI display for this project.

**Comment by kywalda** [comment]
for example this:
https://aliexpress.com/item/33015586094.html
choose 3.5" without touch

**Comment by richvanf** [comment]
Thank you very much. I'm currently working on my other issue, modifying the
code to accept GPS and AIS data on UART #0 (using the AIS-mini with its
pass-thru capability from a GPS module), and, later, using UART #1 to
support DSC code from a marine VHF transceiver.
===========================================================
Richard Van Fossan
***@***.***
(253) 230-2525

**Comment by richvanf** [comment]
Have you considered using the RPi Pico W to send data via WiFi to OpenCPN
on a tablet or cell phone?
===========================================================
Richard Van Fossan
***@***.***
(253) 230-2525

**Comment by richvanf** [comment]
===========================================================
Richard Van Fossan
***@***.***
(253) 230-2525
As an alternative to changing the processor board, I'm putting together an
AIS-RADAR unit using a NEO-8 GNSS module, an aIS-Mini, an RPi pico, and a
DT-06 serial to WiFi adapter. The AIS-mini has a second serial port, so
I'll route the GNSS data through the AIS mini, freeing up the second serial
port on the Pico to drive the DT-06 for use by OpenCPN or other
applications on a tablet, cell phone, or laptop.

**Comment by richvanf** [comment]
Have you considered this display
<https://www.amazon.com/gp/product/B0953BL9WK?ie=UTF8&psc=1>  unit? Also,
the dAISy Mini with a GPS unit chained to it. That would free up a serial
port for NMEA 0183 output via a TTL-to-RS-422 level converter to connect a
Chart Plotter.

===========================================================
Richard Van Fossan
***@***.***
(253) 230-2525
